[package]
name = "censys-search"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.20.0"
reqwest = {version = "0.11.13", features = ["blocking", "json"]}
serde_json = "1.0"
urlencoding = "2.1.2"
clap = {version = "4.0.32", features = ["derive"]}
